### ISSUE TITLE
Some issues and one suggestion.

### ISSUE THREAD

**Issue by HugoZanco** [VolatilePulse/PoB-Item-Tester#15]
After some tests, I noticed some bugs when pressing some hot keys.

The Ctrl-Windows-C, Ctrl-Windows-U and Ctrl-Windows-D shortcut keys are not working.

The hot keys Ctrl-Windows-Alt-C and Ctrl-Windows-Alt-D are working well.

In the build selection window, when the option "Use the last used PoB build" is checked and the "ok" key is pressed, the next open window does not relate to any build, it shows only the copied item.
A very common error that occurs when opening the next window is that, when it opens, it is in a position where it is not possible to select its top (where the button to close the window is) and, consequently, cannot be dragged.

I also found that the "Magic Damage increased while wielding a Staff" and "#% to Global Critical Strike Multiplier" mods is missing from DPS Search. Perhaps other "while wielding", "with one/two handed Weapons" and "Critical Strike" mods are also missing. 

Now a suggestion of mine.
It may be interesting to add a way in which the user can specify whether he wants the ES or the life mods must to be present. But, this tool is working just fine without it.

Do you want the next suggestions and feedbacks to be included in reddit or in git? Anyway, I'll be posting it's here and there.

Again, thanks dude! Congratulations for this great tool!

**Comment by coldino** [comment]
For your hotkeys, which version of Windows do you run?

As for your suggestion - the site already has a field for adding empty sections. This intended as a space for you to add whatever custom selectors you would like.

I'll let Xan comment on the mods as I'm out of touch and know he's been looking at mods as part of the latest update.

In future a separate issue per topic is easier to manage for us 😃

**Comment by HugoZanco** [comment]
I am using Windows 10.

**Comment by xanthics** [comment]
Due to change in how search complexity is calculated, I elected to remove the option to prepend "and" sections.  The default search is 55 and +5 for each weighted mod(max 29 weighted).  So added an "and" section(or anything else, removes a possible weighted sum.  I'll take a further look at that though.

I'm currently evaluating the "weapon specific" jewel mods, as I think I messed up on parsing them.  Updates will be posted to the webpage repo.

**Comment by HugoZanco** [comment]
Around the mod "Global Critical Strike Multiplier", in the Weighted page shows the value 1516.3 for the mod, but when the search for All Jewel base is generated, the mod "#% to Global Critical Strike Multiplier" does not appear.
You can see the search returned here: https://www.pathofexile.com/trade/search/Delirium/JZyJK0rIl

Thanks for the quick responses!

**Comment by xanthics** [comment]
> 
> 
> Around the mod "Global Critical Strike Multiplier", in the Weighted page shows the value 1516.3 for the mod, but when the search for All Jewel base is generated, the mod "#% to Global Critical Strike Multiplier" does not appear.
> You can see the search returned here: https://www.pathofexile.com/trade/search/Delirium/JZyJK0rIl
> 
> Thanks for the quick responses!

That should be fixed now, along with any other missing mods.

**Comment by VolatilePulse** [comment]
Sorry that there was no follow up on the hotkeys not working. They do appear to work fine during development and for other users. The most common issue is that the Windows key is disabled on your keyboard, but that doesn't appear to be the issue here. If you're still having issues, please reopen this issue and post some information on what isn't working. Does the DPS search window not open unless you update your build first? Does the program no respond at all for you with the hot keys you listed?
