### ISSUE TITLE
ctrl+win+D not working 

### ISSUE THREAD

**Issue by btrisler** [VolatilePulse/PoB-Item-Tester#18]
When I push CTRL+Win+D or CTRL+ALT+Win+D I get a notification for generating DPS search, but it never opens a page or does anything.

I'm wondering how to debug.  Perhaps it doesn't like chrome browser?

**Comment by xanthics** [comment]
(Not a dev of the ahk tool)

Are you using the installed or portable version of PoB?  If you are using the installed version try the following troubleshooting steps (from discord).

```
1) Unzip the portable .zip version of the fork to a nice simple directory like C:\POBFORK
2) Fire up *that* version of PoB, open Options (bottom right) and set the 'Build save path' to match your installed one
3) Exit PoB-Item-Tester, then go into its install folder and open TestItem.ini in an editor like notepad
4) Change the values for PathToPoB and PathToPoBInstall to point at your portable install folder like C:\POBFORK
5) Make sure the BuildDirectory value is pointing at your builds folder
6) Test it!
```

**Comment by btrisler** [comment]
I'm using installed POB community fork

I tried these things and they didn't work.

Brian Trisler
http://www.briantrisler.com
- A work in progress

**Comment by VolatilePulse** [comment]
Sorry for the delayed response. I hope you've either figured it out or switched to using the portable version. If you haven't and are still looking for assistance, please reopen this issue as I'm curious to see what the problem actually is.

**Comment by btrisler** [comment]
What do you mean portable version?

**Comment by VolatilePulse** [comment]
As far as we are aware, the only reason the DPS search window doesn't appear is due to issues of locating crucial PoB files. There is a currently known issue with using the installed version of the community version of PoB, but the portable, or zipped version, is known to work fine. I assume that the rest of the program works fine; selecting a build, configuring settings in the UI, etc.

I exclusively use Chrome and it launches fine for me and other users and developers that also use chrome so that isn't the issue. Does the item tester work (CTRL + WIN + C)?

**Comment by VolatilePulse** [comment]
With the testing that I did this morning, OpenArl's PoB and the PoB Community fork both work with their installed or portable versions. Since I haven't heard back from you in over a week. I'll close this again. If you're still using the program and need more assistance, we recommend doing a fresh install of PoB (or use the portable version) to ensure there are no issues.

Every feature works as intended, even with using Chrome so there may be an indication something is broken on your end and we can try and troubleshoot the issue once more information is provided.
