### ISSUE TITLE
Issue with exporting 3.12 trees from path of building community

### ISSUE THREAD

**Issue by GaretWebster** [VolatilePulse/PoB-Item-Tester#22]
I am sorry I don't have specific replication steps for this issue, but both my friend and I have been having issues importing this patch.

It's very inconsistent, we both are able to sometime import our characters, and sometimes unable to. When an import fails no new tab is created, and all the weights are left at zero.

Best attempt at replication steps:
Ensure testitem.ahk is running
Open path of building community
Import character from account "gdubrocks"
Press start
Select GDUB_AURA
Press done
Save build
Navigate to https://xanthics.github.io/PoE_Weighted_Search/
Hit ctrl + alt + windows + D
Select build GDUB_AURA
it will "load" but no new tab will create, and all weights will be left at zero

**Comment by VolatilePulse** [comment]
First off, I'm sorry you are experiencing some issues with the script. As this is mostly a program that relies on another program (PoB specifically) to work, there are some odd interactions that can occur and we have been trying to resolve issues when they crop up. 

Secondly, with that said, I just released a change to the script early this morning/late last night that adds error reporting when one of the scripts encounters and issue and should return the error output of any failures shy of a Windows issue. If you download the lastest version (and just override your existing files) you should get an error message if it's something between our scripts or PoB's. 

Lastly, you aren't required to have the DPS search (Dan's webpage) open in order to use it. Once you press the hotkey (CTRL + WIN + D), the script will do some magic and should automatically open a new search result for you.

If you encounter the issue again after the latest version change, please reply with the error output and we will try to better assist you.

**Comment by GaretWebster** [comment]
Very helpful thanks. 

C:\Users\Garet\Documents\My Games\Path of Exile\PoB-Item-Tester-master\bin\luajit.exe: ...of Exile\PoB-Item-Tester-master\ItemTester\SearchDPS.lua:141: attempt to index field 'displaySkillList' (a nil value)
stack traceback:
	...of Exile\PoB-Item-Tester-master\ItemTester\SearchDPS.lua:141: in main chunk
	[C]: at 0x004020f0

My inital guesses were this has to do with new skill gems, or the glove enchantment edict of the grave.

The new skill gems currently don't show in PoB so I am not sure why they would cause this issue.

I removed all skill gems except for divine ire from my build and I still got this error.

**Comment by coldino** [comment]
I know it sounds simple, but could you make sure you have a skill selected in the left-hand pane of PoB and ensure you have saved before trying again?

The mention of `displaySkillList` in the error might indicate some sort of issue with skill selection.

**Comment by GaretWebster** [comment]
I do.
![image](https://user-images.githubusercontent.com/5297647/94179552-870fff00-fe51-11ea-99c6-c68149fc6988.png)

**Comment by GaretWebster** [comment]
Here is the build file.
https://pastebin.com/BNxC55iz

and the actual export
https://pastebin.com/VjA3uRm2

**Comment by VolatilePulse** [comment]
A couple of last pieces of information that may be helpful is; Which version of PoB are you using? Are you using the original PoB or the Community Edition? And do you use the installer or the portable, zip archive?

I doubt these issues specifically will alter the outcome, but the fact that you and someone else is having issues with different builds could help pinpoint what the issue is if we can reproduce the issue. We may have further requests for information if we can't figure out the issue though.

**Comment by GaretWebster** [comment]
Path of building community fork version 1.4.170.11 (latest).

I believe I used the installer, My install directory is C:\Program Files (x86)\Path of Building Community

**Comment by GaretWebster** [comment]
[General]
PathToPoBInstall=C:\Program Files (x86)\Path of Building Community
PathToPoB=C:\ProgramData\Path of Building
BuildDirectory=C:\Users\Garet\Documents\Path of Building\Builds
CharacterBuildFileName=Aura2.xml


Strange the path to PoB is different. Maybe this is causing my issue?

**Comment by VolatilePulse** [comment]
I'll have to do some digging to find out for sure, but it looks like there might be some left over files from when you had PoB installed previously. To verify, navigate to `C:\Program Data` in File Explorer and see if there is also a `Path of Building Community` directory. If there is, assuming you no longer use the original PoB, you can safely delete the `Path of Building` directory. That should be sufficient to force the AHK script to request PoB be opened again the next time you launch it. If it doesn't prompt you and things still don't work, delete the item tester's in config file.

Let us know if this resolved the issue. In the meantime, I have a specific use case to try and fix now.

**Comment by GaretWebster** [comment]
I haven't had the regular version of path of building installed for over a year, and the script has worked since I removed it so I don't think that is the issue. It didn't fix it when I restarted the script.

**Comment by VolatilePulse** [comment]
Darn, I was hoping it was something simple. I'm currently at work and will be home in about 90 minutes. I don't know if it's easier for you or not, but there is a link to our Discord server on the main GitHub page and in the README. Either way, I'll take a look at it once I'm home and see if I can reproduce this issue and get back to you.

**Comment by GaretWebster** [comment]
Ill check out the discord.

I think I have ruled out it being the TestItem.ini.

I deleted the file, and it regenerated with the exact same data.

I manually changed the path to path of building community and that didn't fix the issue either.

**Comment by Razunter** [comment]
> I'll have to do some digging to find out for sure, but it looks like there might be some left over files from when you had PoB installed previously. To verify, navigate to `C:\ProgramData` in File Explorer and see if there is also a `Path of Building Community` directory. If there is, assuming you no longer use the original PoB, you can safely delete the `Path of Building` directory. That should be sufficient to force the AHK script to request PoB be opened again the next time you launch it. If it doesn't prompt you and things still don't work, delete the item tester's ini config file.

I've had the `displaySkillList` bug too.
I use the Community version and there were no `C:\ProgramData\Path of Building Community` folder. I think it used the original one before I removed it. Now PoB created the `Path of Building Community` folder, but on the wrong drive )
Still, it fixed my issue.

**Comment by coldino** [comment]
I believe all of these issues are no longer relevant with recent PoB installers and our new detection code.
