### ISSUE TITLE
pobinterface.lua:40: attempt to index field 'displaySkillList' (a nil value)

### ISSUE THREAD

**Issue by flapanther33781** [VolatilePulse/PoB-Item-Tester#27]
Hi there.  I used your tool once a few weeks ago and found it very handy.  I thought I would try to re-use it again now to see if its suggestions changed at all based on my build changing over the last few weeks, but when I run the script it gave an error stating the response to 'displaySkillList' was a nil value.  I noticed I had not set my main skill in PoB, so I did that, saved the build, and re-ran your tool, however I am still getting the same error.

I closed and re-ran both PoE and your tool and I'm still getting the error.  I thought I would contact you first before trying to uninstall/reinstall.  Do you have any suggestions?

**Comment by therber2** [comment]
I am getting a similar error that I wasn't before after just downloading this last update, here is the code
`C:\PoB-Item-Tester-master\bin\luajit.exe: C:\PoB-Item-Tester-master\ItemTester\mockui.lua:232: attempt to index field 'calcsTab' (a nil value)
stack traceback:
	C:\PoB-Item-Tester-master\ItemTester\mockui.lua:232: in main chunk
	[C]: in function 'dofile'
	C:\PoB-Item-Tester-master\ItemTester\SearchDPS.lua:15: in main chunk
	[C]: at 0x004020f0
`

**Comment by coldino** [comment]
We believe both of there issue are caused by odd PoB installers, which were supplied for just two versions a while ago. This still causes problems even if PoB is fully updated afterwards.

 1) Make a note of your builds folder
 1) Uninstall PoB
 1) Download a fresh copy of PoB and install it

I will try to detect more of these issue and display a more useful error message.

Of course if this didn't solve the problem for you please reopen the issue and include the content of item tester's ini file and the new error message.
