### ISSUE TITLE
Weights are not generated for General's Cry builds

### ISSUE THREAD

**Issue by washow** [VolatilePulse/PoB-Item-Tester#28]
Using the latest repo, I tried to get the weights for different builds and noticed that it's not generating weights for General's Cry builds. 

It correctly reads the pob and the main skill but all the fields' weight are 0.

**Comment by xanthics** [comment]
This appears to be a bug with PoB itself.  The only value on the tree that is generating dps values is exerted attack damage%.  Until that is fixed in PoB, not using FullDPS still generates relatively correct weights.

![image](https://user-images.githubusercontent.com/3137623/116453097-4deaa380-a813-11eb-8610-1897b7929fdf.png)

**Comment by coldino** [comment]
Similar to #29. Latest changes to item tester do as much as we can until PoB is fixed, so closing this issue.
