### ISSUE TITLE
It doesn't work on this item and I don't know why

### ISSUE THREAD

**Issue by myrahz** [VolatilePulse/PoB-Item-Tester#31]
I was just showing off this tool to a friend and he wasn't able to get it to work. Apparently it was a specific problem to this item and only this version of it as other versions worked and I couldn't find the reason to fail.

> D:\Funny Tools\PoE\itemtester\bin\luajit.exe: D:\Funny Tools\PoE\itemtester\ItemTester\mockui.lua:322: attempt to index local 'txt' (a nil value)
> stack traceback:
> 	D:\Funny Tools\PoE\itemtester\ItemTester\mockui.lua:322: in function 'lineToHtml'
> 	D:\Funny Tools\PoE\itemtester\ItemTester\mockui.lua:310: in function 'AddLine'
> 	Classes/ItemsTab.lua:2447: in function 'AddItemTooltip'
> 	D:\Funny Tools\PoE\itemtester\ItemTester\TestItem.lua:50: in main chunk
> 	[C]: at 0x004020f0
> Path: C:\Users\hugoc\OneDrive\Documentos\Path of Building\Builds\3.14\ENDGAME GG.xml
> Build: 3.14\ENDGAME GG
> Skill: Weapon 1 Lightning strike / Lightning Strike / Melee hit

Item clipboard:

> Item Class: Warstaves
> Rarity: Unique
> Cane of Kulemak
> Serpentine Staff
> --------
> Warstaff
> Quality: +48% (augmented)
> Physical Damage: 212-442 (augmented)
> Critical Strike Chance: 6.30%
> Attacks per Second: 1.66 (augmented)
> Weapon Range: 13
> --------
> Requirements:
> Level: 68
> Str: 85
> Int: 85
> --------
> Sockets: R B-R-R 
> --------
> Item Level: 85
> --------
> +20% Chance to Block Attack Damage while wielding a Staff (implicit)
> --------
> 66% increased Unveiled Modifier magnitudes
> 230% increased Physical Damage
> +74% to Physical Damage over Time Multiplier
> 33% increased Attack Speed
> 38% chance to Impale Enemies on Hit with Attacks
> +28% to Quality
> --------
> Stolen power is still power.
> --------
> Note: ~price 0 exalted
> 

Other Cane of Kulemak work, same with Physical Damage over Time Multipler work, same for Impale and other 0 priced items, so I can't really figure out what stat is causing it.

**Comment by VolatilePulse** [comment]
I took a look at this a bit today. This issue is really interesting. The same exact item works if the word `exalted` is omitted. This is some weird bug that is happening within another portion of the program that I'm not overly familiar with. I've passed it on to the other developer to see if he can work out why that is causing issues here.

**Comment by coldino** [comment]
PoB is acting oddly with that note line. In original form PoB does not display it (which is wrong because it usually shows note/price lines). Just taking one space out of the line makes PoB display it again.

It was delivering us a null line in the tooltip. The UI system obviously handles that without crashing, but we didn't. Adding a simple fall-back to an empty string fixed it.

**Comment by myrahz** [comment]
Thanks, just wanted to share it, and thank you all for continuing to support this tool, it is really amazing and underrated!
